### ISSUE TITLE
User story: access to a fact sheet about self esteem

### ISSUE THREAD

**Issue by marisid** [CYPIAPT-LNDSE/social-up#10]
**As an** adolescent browsing social media,
**I would like** to have access to a fact sheet about self esteem,
**so that** I can check my own thinking patterns.

**Comment by MatteoTurco** [comment]
What about: so that I can track my own thinking patterns

It sounds more generally applicable to me.

**Comment by marisid** [comment]
I would think that "track" is more about recording (which won't be the case when the user just accesses a fact sheet) whereas "check" is more about comparing the user's thinking patterns with actual facts. What about *so that I can check my own thinking patterns* ?

**Comment by MatteoTurco** [comment]
Perfect!
