### ISSUE TITLE
Add user stories based on wireframes

### ISSUE THREAD

**Issue by msachi** [CYPIAPT-LNDSE/social-up#4]
I've uploaded mine and Marina's crazy 8s, still need to get Matteo's. Then we can convert them into user stories.

**Comment by marisid** [comment]
@MatteoTurco could you drag and drop your crazy 8s A4 sheet in a comment below so that we can add it to the project and reconstruct the user journey / stories you suggested?

**Comment by MatteoTurco** [comment]
@marisid I'm afraid I don't know what you mean by drag and drop - besides I do not have access to a scanner, nor do I have access to a working laptop today, as the entire system is down for the day. Hooray.

What I can do is take a picture of the sheet with my phone and email it over to you. Or please do let me know of a better way.

**Comment by msachi** [comment]
No worries @MatteoTurco, if you take a photo with your phone and e-mail it over that would be great ☺️ In case you don't have it at hand, my e-mail is marko@foundersandcoders.com

**Comment by marisid** [comment]
All crazy 8s added and user stories created as separate issues.
