### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by rebeccaradding** [CYPIAPT-LNDSE/social-up#6]
Hey all, when @sofer and I were cleaning up the FAC repositories earlier this month, we tried to standardize naming conventions using dwyl's example.

It's a small things, but would you mind renaming `SocialUp` as `social-up`? Apologies if you are already aware of the convention but decided to use caps on purpose!

**Comment by marisid** [comment]
Yes, sure no problem! We weren't aware of this naming convention.
